[build]
  command = "pnpm build:bookbat"
  publish = "dist/bookbat"
  ignore = "bash scripts/netlify-ignore-bookbat.sh"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=(self)"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
